---
id: rubykaigi-2023
base_name: slide
tags: ['ruby', 'python', 'rubykaigi', 'quic']
presentation_date: '2023-05-12'
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: ['MIT']
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
author:
  markup_language: :rd
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user:
  speaker_deck_user:
source_code_url: https://github.com/unasuke/rubykaigi-2023
